version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gopkg.in/auth0.v5
    versions:
    - 5.11.0
    - 5.13.0
    - 5.14.1
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
    - 1.8.0
